### ISSUE TITLE
Invalid AFG subtree for codec Conexant CX11970?

### ISSUE THREAD

**Issue by ni-ka** [gm-vm/hda-analyzer#1] opened 2022-10-30 13:39 UTC
here is what i get when I run the program

```
Invalid AFG subtree for codec Conexant CX11970?
Traceback (most recent call last):
  File "/home/nils/Documents/projects/dev/hda-analyzer/hda-analyzer/hda_analyzer.py", line 549, in <module>
    sys.exit(main(sys.argv))
  File "/home/nils/Documents/projects/dev/hda-analyzer/hda-analyzer/hda_analyzer.py", line 526, in main
    if read_nodes(sys.argv[1:]) == 0:
  File "/home/nils/Documents/projects/dev/hda-analyzer/hda-analyzer/hda_analyzer.py", line 92, in read_nodes
    read_nodes2(c.card, i)
  File "/home/nils/Documents/projects/dev/hda-analyzer/hda-analyzer/hda_analyzer.py", line 72, in read_nodes2
    c.analyze()
  File "/home/nils/Documents/projects/dev/hda-analyzer/hda-analyzer/hda_codec.py", line 1171, in analyze
    func = self.param_read(nid, PARAMS['FUNCTION_TYPE'])
  File "/home/nils/Documents/projects/dev/hda-analyzer/hda-analyzer/hda_codec.py", line 1067, in param_read
    return self.rw(nid, VERBS['PARAMETERS'], param)
  File "/home/nils/Documents/projects/dev/hda-analyzer/hda-analyzer/hda_codec.py", line 1051, in rw
    res = ioctl(self.fd, IOCTL_VERB_WRITE, struct.pack('II', verb, 0))
struct.error: 'I' format requires 0 <= number <= 4294967295

```

**Comment by gm-vm** [comment] 2022-10-30 14:35
I think this can only happen if `nid >= 256` [here](https://github.com/gm-vm/hda-analyzer/blob/60c6ec7d3d87d359b4a5996b6c3e2fb546a4c975/hda-analyzer/hda_codec.py#L1047).

Try running the following command in a terminal:
```sh
for codec in /proc/asound/card*/codec#*; do printf "\n$codec\n"; cat "$codec" | grep Node; done
```

This should dump all the nodes of all the cards.

From the [HDA specification](http://www.intel.com/content/dam/www/public/us/en/documents/product-specifications/high-definition-audio-specification.pdf):
> Nominally, a NID is represented in a “short-form” as a 7-bit integer. However, in very large codecs
(e.g., containing more than 127 nodes), NIDs may be represented in a “long-form” as a 15-bit
integer

My suspect is that you need this "long-form" and that hda-analyzer does not support it.

**Comment by ni-ka** [comment] 2022-10-30 15:19
Wow, you are quick @gm-vm, thanks!

Not sure if the command is correct, here is the output:
```

/proc/asound/card0/codec#0

/proc/asound/card0/codec#2
```
Let me know ifyou need anything else

**Comment by gm-vm** [comment] 2022-10-30 15:23
That is weird, I would have expected some output. Can you try this instead?
```sh
cat "/proc/asound/card0/codec#0" "/proc/asound/card0/codec#2"
```

**Comment by ni-ka** [comment] 2022-10-30 15:43
Here you go!

```
Codec: Conexant CX11970
Address: 0
AFG Function Id: 0x1 (unsol 1)
Vendor Id: 0x14f120d0
Subsystem Id: 0x103c8427
Revision Id: 0x100001
No Modem Function Group found
Default PCM:
N/A
Default Amp-In caps: N/A
Default Amp-Out caps: N/A
State of AFG node 0x01:
  Power: setting=UNKNOWN, actual=UNKNOWN, Error, Clock-stop-OK, Setting-reset
Invalid AFG subtree
Codec: Intel Generic HDMI
Address: 2
AFG Function Id: 0x1 (unsol 0)
Vendor Id: 0x8086280b
Subsystem Id: 0x80860101
Revision Id: 0x100000
No Modem Function Group found
Default PCM:
N/A
Default Amp-In caps: N/A
Default Amp-Out caps: N/A
State of AFG node 0x01:
  Power: setting=UNKNOWN, actual=UNKNOWN, Error, Clock-stop-OK, Setting-reset
Invalid AFG subtree
```
I don't like the last line...

**Comment by gm-vm** [comment] 2022-10-30 15:58
I was probably wrong about the long-form thing then.

[Here](https://github.com/torvalds/linux/blob/882ad2a2a8ffa1defecdf907052f04da2737dc46/sound/pci/hda/hda_proc.c#L795-L800) is where the kernel is failing. hda-analyzer's [`get_sub_nodes`](https://github.com/gm-vm/hda-analyzer/blob/60c6ec7d3d87d359b4a5996b6c3e2fb546a4c975/hda-analyzer/hda_codec.py#L1069-L1072), the function returning the supposedly invalid `nid`, is basically the translation of the kernel's [`snd_hdac_get_sub_nodes`](https://github.com/torvalds/linux/blob/882ad2a2a8ffa1defecdf907052f04da2737dc46/sound/hda/hdac_device.c#L347-L369), which is what runs when you read `/proc/asound/card*/codec#*`.

I can see your card mentioned in the git log, so it should be supported: https://github.com/torvalds/linux/commit/744a11abc56405c5a106e63da30a941b6d27f737

I don't know what is going on, but the fact that not even the kernel can get the list of nodes makes me think the issue is somewhere else.

**Comment by ni-ka** [comment] 2022-10-30 16:22
Got it, i do have some sound issues (for a while now, too busy to investigate) and various messages in system log regarding codecs, like:
`10.122339]` snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380` or
`[   14.951316] snd_hda_intel 0000:00:1f.3: No response from codec, disabling MSI: last cmd=0x20270503`

I just opened a new issue report on the Manjaro forums which has alsa-info.sh appended: https://forum.manjaro.org/t/speaker-sometimes-only-left-and-mic-not-working-on-hp-zbook-g5-studio-bang-olufsen/125515. 

I'll probably also try on a live usb just to exclude any local config issues before digging further, if I can confirm it I should prob notify the hda maintainer ? I see quite a few HP special handling in https://github.com/torvalds/linux/blob/f86bfeb689f2c4ebe12782ef0578ef778fb1a050/sound/pci/hda/patch_realtek.c so I guess some special handling might be required

**Comment by gm-vm** [comment] 2022-10-30 16:33
Yes, I would say that reporting a bug on the official bug tracker is the way to go. See the "Kernel driver bugs" section here: https://www.alsa-project.org/wiki/Bug_Tracking

I also suggest attaching the output of `alsa-info.sh` immediately when opening the bug, they'd just ask for it anyway.

PS: since your laptop has a Conexant the quirk will likely end up in `sound/pci/hda/patch_conexant.c`, in case that is what it is needed. The file you linked is for Realtek cards.

**Comment by ni-ka** [comment] 2022-10-30 22:28
Really appreciate the help @gm-vm.

I've tried a couple of live usbs and don't see the issue there (but they run older kernels), I then installed LTS kernel 5.15 and it works fine and my sound issues are gone.

I've filed the following bug report: https://bugzilla.kernel.org/show_bug.cgi?id=216643

**Comment by gm-vm** [comment] 2022-10-31 08:05
One last thing.

Looking better at the output of `alsa-info.sh` I can see that there's something wrong with `pci 0000:01:00.1`. That should be `01:00.1 Audio device [0403]: NVIDIA Corporation GP107GL High Definition Audio Controller [10de:0fb9] (rev a1)`.

I can also see that you have the non-free `nvidia` driver loaded, so I now wonder if that's the source of your problems. That could also explain why Fedora didn't have issues while running 5.19.x.

What happens if you blacklist `nvidia` (check the module is really not loaded with `lsmod`)?

Anyway I'm closing this since I don't think there is something to do in hda-analyzer.

**Closed as completed by gm-vm** 2022-10-31 08:05 UTC
